//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public System.Guid UserId { get; set; }
        public string GroupNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public bool ChiefAdmin { get; set; }
        public bool IdActive { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public string ActivationCode { get; set; }
        public System.DateTime InactiveDate { get; set; }
    }
}
